if(NOT WIN32)
    string(ASCII 27 Esc)
    set(ColourReset "${Esc}[m")
    set(ColourBold  "${Esc}[1m")
    set(Red         "${Esc}[31m")
    set(Green       "${Esc}[32m")
    set(Yellow      "${Esc}[33m")
    set(Blue        "${Esc}[34m")
    set(Magenta     "${Esc}[35m")
    set(Cyan        "${Esc}[36m")
    set(White       "${Esc}[37m")
    set(BoldRed     "${Esc}[1;31m")
    set(BoldGreen   "${Esc}[1;32m")
    set(BoldYellow  "${Esc}[1;33m")
    set(BoldBlue    "${Esc}[1;34m")
    set(BoldMagenta "${Esc}[1;35m")
    set(BoldCyan    "${Esc}[1;36m")
    set(BoldWhite   "${Esc}[1;37m")
endif()

if (EXISTS ${CMAKE_HOME_DIRECTORY}/.env)
    file(STRINGS ${CMAKE_HOME_DIRECTORY}/.env ENV_FILE)
    foreach(VAR ${ENV_FILE})
        string(REGEX MATCH "^[^=]*" KEY ${VAR})
        string(REGEX REPLACE "^[^=]*=" "" VALUE ${VAR})
        set(ENV{${KEY}} ${VALUE})
    endforeach()
    message(STATUS "${Magenta}OSS Region: " $ENV{ENV_CONFIG_OSS_REGION} ${ColourReset})
    message(STATUS "${Magenta}OSS Bucket: " $ENV{ENV_CONFIG_OSS_BUCKET} ${ColourReset})

    add_definitions(-DENV_CONFIG_OSS_ENDPOINT=$ENV{ENV_CONFIG_OSS_ENDPOINT})
    add_definitions(-DENV_CONFIG_OSS_ACCESS_KEY=$ENV{ENV_CONFIG_OSS_ACCESS_KEY})
    add_definitions(-DENV_CONFIG_OSS_ACCESS_KEY_SECRET=$ENV{ENV_CONFIG_OSS_ACCESS_KEY_SECRET})
    add_definitions(-DENV_CONFIG_OSS_REGION=$ENV{ENV_CONFIG_OSS_REGION})
    add_definitions(-DENV_CONFIG_OSS_BUCKET=$ENV{ENV_CONFIG_OSS_BUCKET})
else()
    message(STATUS "${Red} Please create ${Yellow}.env ${BoldBlue}")
    message("ENV_CONFIG_OSS_ACCESS_KEY          \{access_key\}")
    message("ENV_CONFIG_OSS_ACCESS_KEY_SECRET   \{secret_token\}")
    message("ENV_CONFIG_OSS_REGION              \{ap-southeast-1\}")
    message("ENV_CONFIG_OSS_BUCKET              \{buket\}")
    message("${ColourReset}")
endif()